kakao:
  client :
    clientid : 0e6442271cf2844abd1075937a734afa
    redirecturl : http://localhost:8080/auth
    endpoint :
      authurl : https://kauth.kakao.com/oauth/authorize
      tokenurl : https://kauth.kakao.com/oauth/token
  resource :
    sign : https://kapi.kakao.com/v1/user/signup
    userinfo : https://kapi.kakao.com/v2/user/me

naver:
  client :
    clientid : loeEuLjELiQua4L2VFl2
    clientsecret : 9i_fTDRtVp
    redirecturl : http://localhost:8080/auth
    endpoint :
      authurl : https://nid.naver.com/oauth2.0/authorize
      tokenurl : https://nid.naver.com/oauth2.0/token
  resource :
    sign : kapi.kakao.com/v1/user/signup
    userinfo : https://openapi.naver.com/v1/nid/me


